apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 55
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: "my-image:1.2.3"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
